### ISSUE TITLE
Panel material

### ISSUE THREAD

**Issue by tigert** [zlsa/piper-archer#12]
> < zlsa> tigert, the screenshots at http://tigert.1g.fi/kuvat/Simulators/Flightgear/gauge-faces/ show a sort of flat sheet panel material; what does it look like at the edges?

It's painted aluminium I think. It's flat on the edges too, with screws on the edges. This image shows it pretty well:
http://ingonokasharedpictures.s3.amazonaws.com/Blog/2013-10-20%20-%20Selling%209MDRJ/Panel%20HighRes%20%20026.jpg

This is the "new piper" Archer (the HSI photo was from a Saratoga) - but before the G1000" era, I think those photos were taken around 2004 or so.

I did some digging of those photos and noticed I had some more pics with wider view of the whole panel as well, I have uploaded them to the same folder:

http://tigert.1g.fi/kuvat/Simulators/Flightgear/gauge-faces/

//T

**Comment by zlsa** [comment]
Thanks a lot for the new pictures - a big reason it's hard to make an accurate panel is that each airplane is slightly different. Having pictures of one panel, from one aircraft, is very nice.

Which panel (plastic or aluminum) do you think is more "common"/better/more used?

**Comment by zlsa** [comment]
I'll rename the Piper Archer CX to the Piper Archer III, then follow your images (of OH-PYC) for the interior.

**Comment by tigert** [comment]
The older aircraft had usually the molded platic panel, new generation has flat machined metal panels. Nowadays they all have glass cockpits, but there was this period before glass that the panels in newly produced aircraft were already metal and flat and that brown color. 

There are variants I guess and in older aircraft you have various upgrades and refurbishes and whatever so the panel and the avionics could be whatever.

One way to do it is indeed by picking one aircraft and modelling after that, but it might also be useful to pick one that is close to what it was when it left the factory - so it has chances of being similar to the one you might find reference material for, if you want to use it to learn things.

That is not an OH- reg btw but OY, iirc, it was a sales promo visit by the dealer from Denmark.

**Comment by tigert** [comment]
And being a brand spanking new plane, the setup is likely standard, maybe with some bells and whistles to show off , though :-)

**Comment by zlsa** [comment]
I meant OY, it was a typo... :)

The aluminum panel is still present on the LX/TX glass panels but it's mostly covered by the displays and isn't as visible as on the Archer III.
