### ISSUE TITLE
Won't show up in FGRun

### ISSUE THREAD

**Issue by wlbragg** [zlsa/piper-archer#2]
First I pulled it, then I downloaded the zip, neither will show up in FGRun.
Tried folder names of pa28-181, piper-archer-cx and piper-archer.
I really wanted to test out your rain, fog and ice .nas. Considering using it for my custom CubOS and maybe even the c172p-detailed. Plus I really like all the Pipers, especially non-fiction ones!

**Comment by zlsa** [comment]
This sounds like the same as #1 - can you run `fgfs --aircraft=piper-archer-cx` and tell me what happens?

**Comment by wlbragg** [comment]
I don't run from the command line, I'm on windows. The aircraft won't even show up in the fgrun aircraft list so we never even get to attempt a start-up of any kind, so no log entries or console. I do have a bat file for command line start-up floating around somewhere, I'll see if I can stick your suggestion in it and see if it at leas will run if I point directly to it. But I doubt that will tell us much about why it isn't appearing in fgrun at all.

**Comment by flyingfisch** [comment]
Seems to be working ok in my FGRun (Ubuntu 14.04, FG 3.3)

**Comment by zlsa** [comment]
Is this fixed now?

**Comment by wlbragg** [comment]
Yes, I confirm this is fixed.
